apiVersion: v1
kind: Namespace
metadata:
  name: cai-niao
---
apiVersion: v1
kind: Service
metadata:
  namespace: cai-niao
  name: cn-authorization-center
spec:
  selector:
    app.kubernetes.io/name: cn-authorization-center
  ports:
    - name: http
      port: 9000
      targetPort: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cai-niao
  name: cn-authorization-center-config
data:
  db_host: postgresql-16-1.cai-niao.svc.cluster.local
  db_port: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cai-niao
  name: cn-authorization-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cn-authorization-center
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cn-authorization-center
    spec:
      containers:
      - name: cn-authorization-center
        image: g-ziod8129-docker.pkg.coding.net/mysterious-forest/docker/cn-authorization-center:0.0.1-SNAPSHOT
        ports:
        - name: http
          containerPort: 9000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: cn-authorization-center-config
                key: db_host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: cn-authorization-center-config
                key: db_port
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: cn-pgsql-secret
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cn-pgsql-secret
                key: db_password