apiVersion: v1
kind: Namespace
metadata:
  name: cai-niao
---
apiVersion: v1
kind: Service
metadata:
  namespace: cai-niao
  name: cn-authorization-center
spec:
  selector:
    app.kubernetes.io/name: cn-authorization-center
  ports:
    - name: http
      port: 9000
      targetPort: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cai-niao
  name: cn-authorization-center-config
data:
  DB_HOST: postgresql-16-1.cai-niao.svc.cluster.local
  DB_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cai-niao
  name: cn-authorization-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cn-authorization-center
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cn-authorization-center
    spec:
      containers:
      - name: cn-authorization-center
        image: registry.mcainiaom.top/cn-authorization-center:1.0.0
        ports:
        - name: http
          containerPort: 9000
        envFrom:
        - configMapRef:
          name: cn-authorization-center-config
        - secretRef:
          name: cn-pgsql-secret